"""
ticket_builder.py — Assemble the final Jira ticket draft as ADF JSON.

This is READ/DRAFT only. The JSON produced here is meant for human review
before a developer manually files it in Jira.

ADF reference: §9 of the Jira REST API Reference doc.
FLIPPI field reference: §10 of the Jira REST API Reference doc.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .agent_parser import BugReport
from .agent_scorer import SeverityResult
from .tfidf_similarity import SimilarityResult

# FLIPPI project constants (§10 of API reference)
FLIPPI_PROJECT_KEY = "FLIPPI"
BUG_ISSUE_TYPE_ID = "10036"

# Jira component name → team label shown in triage notes
# Component names match exactly what's in FLIPPI project (verified 2026-06-10)
JIRA_COMPONENTS = {
    "Backend":      {"id": "14386", "team": "BE_Flippi"},
    "Backend-Labs": {"id": "14385", "team": "BE_Labs"},
    "DS":           {"id": "14384", "team": "DS"},
    "UI":           {"id": "14383", "team": "UI"},
    "immersive":    {"id": "14387", "team": "Immersive"},
    # "bugs" → no Jira component set; ticket goes to triage queue for manual routing
}

# component_hint (from agent_parser) → Jira component name
# hint is already the Jira component name for our 5 teams; "bugs" means unclassified
VALID_JIRA_COMPONENTS = set(JIRA_COMPONENTS.keys())


@dataclass
class TicketDraft:
    jira_payload: dict          # ready-to-POST Jira JSON (fields only)
    display_summary: str        # human-readable summary string
    triage_notes: dict          # metadata not in the ticket itself


def build_ticket(
    bug: BugReport,
    severity: SeverityResult,
    similarity: SimilarityResult,
) -> TicketDraft:
    """
    Assemble a Jira ticket draft from parsed bug, severity score,
    and similarity results.
    """
    jira_component, team_label = _resolve_component(bug.component_hint)
    description_adf = _build_description_adf(bug, severity, similarity)

    fields: dict = {
        "project":              {"key": FLIPPI_PROJECT_KEY},
        "issuetype":            {"id": BUG_ISSUE_TYPE_ID},
        "summary":              bug.title,
        "priority":             {"id": severity.priority_id},
        "description":          description_adf,
        "labels":               _build_labels(bug, team_label),
        "customfield_10331":    {"value": severity.severity},  # Severity field
    }

    # Component (only set when classified; "bugs" = unclassified, left blank)
    if jira_component:
        fields["components"] = [{"name": jira_component}]

    # Suggested assignee (display name only — accountId needed for real filing)
    if similarity.suggested_owner:
        fields["_suggested_assignee_display"] = similarity.suggested_owner

    # Duplicate hint
    if similarity.duplicate_of:
        fields["_duplicate_candidate"]   = similarity.duplicate_of
        fields["_duplicate_confidence"]  = similarity.duplicate_confidence

    triage_notes = {
        "team":                  team_label,
        "jira_component":        jira_component or "unclassified (needs manual routing)",
        "priority_scoring_path": severity.scoring_path,
        "severity_justification": severity.justification,
        "owner_suggestion":      similarity.suggested_owner,
        "owner_reason":          similarity.owner_reason,
        "duplicate_of":          similarity.duplicate_of,
        "duplicate_confidence":  similarity.duplicate_confidence,
        "similar_bugs": [
            {
                "key":        m.key,
                "url":        m.url,
                "summary":    m.summary,
                "similarity": m.similarity,
                "assignee":   m.assignee,
                "priority":   m.priority,
            }
            for m in similarity.top_matches
        ],
        "note": (
            "This draft was generated by the SLAP triage prototype. "
            "A human must review and file the actual Jira ticket. "
            "Auto-create is OFF by design."
        ),
    }

    return TicketDraft(
        jira_payload={"fields": fields},
        display_summary=bug.title,
        triage_notes=triage_notes,
    )


# ---------------------------------------------------------------------------
# ADF builders
# ---------------------------------------------------------------------------

def _build_description_adf(
    bug: BugReport,
    severity: SeverityResult,
    similarity: SimilarityResult,
) -> dict:
    """Build the full ADF description node."""
    content = []

    # --- Triage banner ---
    content.append(_paragraph(
        [_text("Auto-drafted by SLAP Triage Agent. ", bold=True),
         _text("Review before filing. Human must create the actual ticket.")]
    ))

    # --- Bug Description ---
    content.append(_heading("Bug Description", level=3))
    content.append(_paragraph([_text(bug.description)]))

    # --- Impact ---
    content.append(_heading("Impact", level=3))
    content.append(_paragraph([_text(bug.impact)]))

    # --- Steps to Reproduce ---
    content.append(_heading("Steps to Reproduce", level=3))
    if bug.steps_to_reproduce:
        content.append(_ordered_list(bug.steps_to_reproduce))
    else:
        content.append(_paragraph([_text("Not provided.")]))

    # --- Expected vs Actual ---
    content.append(_heading("Expected vs Actual", level=3))
    content.append(_paragraph([
        _text("Expected: ", bold=True), _text(bug.expected_result),
    ]))
    content.append(_paragraph([
        _text("Actual: ", bold=True), _text(bug.actual_result),
    ]))

    # --- Environment ---
    content.append(_heading("Environment", level=3))
    env_lines = [
        f"Platform: {bug.platform}",
        f"App version: {bug.app_version or 'unknown'}",
        f"Reproducibility: {bug.reproducibility}",
    ]
    content.append(_bullet_list(env_lines))

    # --- Severity & Priority ---
    content.append(_heading("Triage Assessment", level=3))
    content.append(_paragraph([
        _text(f"Priority: {severity.priority}  |  Severity: {severity.severity}  |  ", bold=True),
        _text(severity.justification),
    ]))

    # --- Similar Bugs / Duplicate ---
    if similarity.top_matches:
        content.append(_heading("Similar Past Bugs", level=3))
        if similarity.duplicate_of:
            content.append(_paragraph([
                _text(
                    f"Possible duplicate of {similarity.duplicate_of} "
                    f"(confidence: {similarity.duplicate_confidence:.0%}). "
                    "Engineer should verify before filing.",
                    bold=True,
                )
            ]))
        lines = [
            f"{m.key} ({m.priority}, sim={m.similarity:.2f}): {m.summary}"
            for m in similarity.top_matches
        ]
        content.append(_bullet_list(lines))

    # --- Reporter ---
    if bug.reporter_name or bug.reporter_email:
        content.append(_heading("Reporter", level=3))
        reporter = f"{bug.reporter_name or ''} <{bug.reporter_email or ''}>".strip()
        content.append(_paragraph([_text(reporter)]))

    return {"type": "doc", "version": 1, "content": content}


# ---------------------------------------------------------------------------
# ADF node helpers
# ---------------------------------------------------------------------------

def _text(t: str, bold: bool = False) -> dict:
    node: dict = {"type": "text", "text": t}
    if bold:
        node["marks"] = [{"type": "strong"}]
    return node


def _paragraph(inline_nodes: list) -> dict:
    return {"type": "paragraph", "content": inline_nodes}


def _heading(text: str, level: int = 3) -> dict:
    return {
        "type": "heading",
        "attrs": {"level": level},
        "content": [{"type": "text", "text": text}],
    }


def _ordered_list(items: list[str]) -> dict:
    return {
        "type": "orderedList",
        "content": [
            {"type": "listItem", "content": [_paragraph([_text(item)])]}
            for item in items
        ],
    }


def _bullet_list(items: list[str]) -> dict:
    return {
        "type": "bulletList",
        "content": [
            {"type": "listItem", "content": [_paragraph([_text(item)])]}
            for item in items
        ],
    }


# ---------------------------------------------------------------------------
# Component resolver
# ---------------------------------------------------------------------------

def _resolve_component(hint: str) -> tuple[Optional[str], str]:
    """
    Map component_hint (from agent_parser) to (jira_component_name, team_label).

    hint is already the Jira component name for the 5 classified teams.
    'bugs' means unclassified — no Jira component is set, routed to triage queue.

    Returns (jira_component_name_or_None, team_label_string).
    """
    if hint in VALID_JIRA_COMPONENTS:
        meta = JIRA_COMPONENTS[hint]
        return hint, meta["team"]
    # "bugs" or any unrecognised value → unclassified
    return None, "bugs"


def _build_labels(bug: BugReport, team_label: str = "") -> list[str]:
    labels = ["slap", "agentic-triage"]
    if team_label and team_label != "bugs":
        labels.append(team_label.lower().replace("_", "-"))
    platform = (bug.platform or "").lower()
    if "android" in platform:
        labels.append("android")
    if "ios" in platform:
        labels.append("ios")
    return labels
